tasks:
  - name: requirements
    init: |
       pip install -r requirements.txt
       pip install cython
       yes | sudo apt-get install build-essential cmake cython3 libboost-all-dev openmpi-common libfftw3-dev libhdf5-dev libhdf5-dev libhdf5-openmpi-dev libgsl-dev     
    command: |
       mkdir build
       cd build
       cmake ..
       make
